name: com_lvoxx_urban_dictionary
description: "Urban Word Dictionary App"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_bottom_navigation_bar: ^1.3.3
  bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  iconly: ^1.0.1
  icons_plus: ^5.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_theme: ^6.4.1
  logger: ^2.1.0
  path_provider: ^2.1.2
  loading_animation_widget: ^1.2.1
  skeletonizer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/json/app_theme.json

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Light.ttf
          weight: 300
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf
          weight: 400
        - asset: assets/fonts/merriweather/Merriweather-Italic.ttf
          weight: 400
        - asset: assets/fonts/merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/merriweather/Merriweather-Black.ttf
          weight: 900